import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

// Import your custom Navbar component and data client utilities
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { client } from "@/sanity/lib/client";
import { getLayoutData } from "@/lib/content";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch your dynamic layout data
const {
  data: { header, footer },
} = await getLayoutData();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F6F1EA]">
        {/* Render Navbar globally across all page routes if data successfully pulls */}
        {header && <Navbar data={header} />}
        
        {/* Main page content layout views wrapper */}
        <main className="flex-1">
          {children}
        </main>
        {footer && <Footer data={footer} />}
      </body>
    </html>
  );
}